## parse the VERSION file in the sdsl directory 

file(READ "${CMAKE_CURRENT_SOURCE_DIR}/VERSION" LIBRARY_VERSION_FULL)
string(REGEX REPLACE "[\n\r]" "" LIBRARY_VERSION_FULL "${LIBRARY_VERSION_FULL}")
string(REGEX REPLACE "^([0-9]+)\\.[0-9]+\\.[0-9]+$" "\\1" LIBRARY_VERSION_MAJOR "${LIBRARY_VERSION_FULL}")
string(REGEX REPLACE "^[0-9]+\\.([0-9]+)\\.[0-9]+$" "\\1" LIBRARY_VERSION_MINOR "${LIBRARY_VERSION_FULL}")
string(REGEX REPLACE "^[0-9]+\\.[0-9]+\\.([0-9]+)$" "\\1" LIBRARY_VERSION_PATCH "${LIBRARY_VERSION_FULL}")
