name: ASAN

on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

concurrency:
  group: asan-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }} ${{ matrix.cereal == '1' && 'cereal' || '' }}
    if: github.repository_owner == 'xxsds' || github.event_name == 'workflow_dispatch'
    env:
      ASAN_OPTIONS: strict_string_checks=1:detect_stack_use_after_return=1:check_initialization_order=1:strict_init_order=1:detect_leaks=1
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-latest", "gcc-latest"]
        cereal: ["0", "1"]
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup cache
        uses: seqan/actions/setup-actions-cache@main

      - name: Configure tests
        run: |
          mkdir ci_build && cd ci_build
          cmake .. -DCMAKE_BUILD_TYPE=Debug \
                   -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
                   -DCMAKE_C_COMPILER_LAUNCHER=ccache \
                   -DCMAKE_CXX_FLAGS="-pedantic -Wall -Wextra -Werror -fsanitize=address" \
                   -DCMAKE_CXX_STANDARD=23 \
                   -DSDSL_CEREAL=${{ matrix.cereal }}
          make gtest_build

      - name: Build tests
        working-directory: ci_build
        run: |
          ccache -z
          make -k sdsl_test_targets sdsl_examples sdsl_tutorials
          ccache -svvx

      - name: Run tests
        working-directory: ci_build
        run: ctest . -j --output-on-failure --no-tests=error -E 'faust|moby' -R '-im'
